# Generated by ChatGPT

# Findcmark-gfm.cmake
# Locate cmark-gfm library
# This module defines
#  cmark-gfm_FOUND, if false, do not try to use cmark-gfm.
#  cmark-gfm_INCLUDE_DIRS, where to find cmark-gfm.h, etc.
#  cmark-gfm_LIBRARIES, the libraries to link against.

if (cmark-gfm_INCLUDE_DIRS AND cmark-gfm_LIBRARIES)
  # Already in cache, be silent
  set(cmark-gfm_FOUND TRUE)
else ()
  find_path(cmark-gfm_INCLUDE_DIR
    NAMES cmark-gfm.h
    PATHS
      ${CMAKE_INSTALL_PREFIX}/include
      /usr/local/include
      /usr/include
  )

  find_library(cmark-gfm_LIBRARY
    NAMES cmark-gfm
    PATHS
      ${CMAKE_INSTALL_PREFIX}/lib
      /usr/local/lib
      /usr/lib
  )

  include(FindPackageHandleStandardArgs)
  find_package_handle_standard_args(cmark-gfm DEFAULT_MSG
    cmark-gfm_INCLUDE_DIR
    cmark-gfm_LIBRARY
  )

  if (cmark-gfm_FOUND)
    set(cmark-gfm_INCLUDE_DIRS ${cmark-gfm_INCLUDE_DIR})
    set(cmark-gfm_LIBRARIES ${cmark-gfm_LIBRARY})
  endif ()
endif ()

mark_as_advanced(cmark-gfm_INCLUDE_DIR cmark-gfm_LIBRARY)
